

// comment for document 1
// you can write any info here
// such as: 
// ⚠️ DO NOT EDIT THIS FILE
// ⚠️ THIS FILE WAS AUTO GENERATED
// ⚠️ ANY MODIFIED CONTENT WILL BE LOSE

// comment for SHOULD_CHECK_UPDATE pre-line
export const SHOULD_CHECK_UPDATE = false as const

// multi line comment 1
// multi line comment 2
export const DATA_IS_MAP = {"a":1,"b":2} as const

export const DATA_IS_ARRAY = [1,2] as const

// multi line comment 1
// multi line comment 2
// all mode in one same key-value
// string 1
export const ALIAS_NAME = "cool project" as const

// string 2
export const STRING = "singleString" as const

// integer
export const NUMBER = 123 as const // last pair comment
// negative number
export const NEGATIVE_NUMBER = -123.4 as const
// float
export const FLOAT = 2.333 as const
// intHex
export const INT_HEX = 16711731 as const
// ⚠️ NaN with dot(.)
export const NOT_A_NUMBER = NaN
// ⚠️ Infinity with dot(.)Inf
export const INFINITY = Infinity
export const NEGATIVE_INFINITY = -Infinity

// ❌ `undefined` is fail, please use `null` instead
export const UNDEFINED = "undefined" as const

// null
export const NULL_VAR = null

// object
// ⚠️ { key: (there must be space symbol) value }
export const OBJECT = {"a":1,"b":2} as const

// array
export const ARRAY = [1,2,3,4] as const
 // comment up split line

// ============ comment for document 2 ============

export const DOC2 = true as const // is DOC2 end comment exist

export const USE_WILDCARD = true as const

// load env from process.env with js template strings
export const ENV_FORM_PROCESS_ENV = "${asdf}" as const

